# Generated by Django 3.0.5 on 2020-04-23 15:44

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tittle', models.CharField(db_index=True, max_length=256, unique_for_date='published_at')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('main_text', models.TextField()),
                ('image', models.ImageField(blank=True, height_field='height_field', help_text='uplaod image', null=True, upload_to='post', width_field='width_field')),
                ('width_field', models.PositiveIntegerField(blank=True, default='1080', null=True)),
                ('height_field', models.PositiveIntegerField(blank=True, default='720', null=True)),
                ('main_file', models.FileField(blank=True, null=True, upload_to='resume_file')),
            ],
        ),
    ]
